version: 0.1
log:
  level: info
  formatter: text
  fields:
    service: registry


storage:
    filesystem:
        rootdirectory: /var/lib/registry
#   s3:
#     accesskey: 
#     secretkey:
#     region: us-east-1
#     bucket: docker.registry-dev.sagebase.org
#     encrypt: true
#     secure: true
#     v4auth: true
#     chunksize: 5242880
#     rootdirectory: /
#   cache:
#     layerinfo: inmemory



auth:
  token:
    realm: https://192.168.99.100:8443/dockerauth-1.0/dockerAuth
    service: my.registry.com
    issuer: registry.com
    rootcertbundle: /etc/docker/registry/cert.pem



http:
  addr: :5000
  secret: asecretforlocaldevelopment
#  host: https://myregistryaddress.org:5000
#  tls:
#    certificate: /path/to/x509/public
#    key: /path/to/x509/private
#    clientcas:
#      - /path/to/ca.pem
#      - /path/to/another/ca.pem


notifications:
  endpoints:
    - name: aListener
      disabled: false
      url: http://192.168.99.100:8080/dockerauth-1.0/dockerNotify
#      headers: <http.Header>
      timeout: 20s
      threshold: 5
      backoff: 10s
